// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gopweevwodjnibamlcuf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdvcHdlZXZ3b2RqbmliYW1sY3VmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzMwNTAxOTQsImV4cCI6MjA4ODYyNjE5NH0.m7olp52FwzljWa1lLif_CGzOgZfXMC7PE37ipjzlKpY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});